import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const portArgIndex = args.findIndex((arg) => arg === '--port');
const port = portArgIndex !== -1 && args[portArgIndex + 1]
  ? Number(args[portArgIndex + 1])
  : Number(process.env.PORT) || 3009;

const prefix = '/Megacubo';
// Serve the GitHub Pages deploy folder generated by build-ghpages.mjs.
const publicDir = path.join(__dirname, '..', 'build', 'Megacubo');

const contentTypes = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
  '.ttf': 'font/ttf',
  '.ico': 'image/x-icon',
};

function getContentType(filePath) {
  return contentTypes[path.extname(filePath).toLowerCase()] || 'application/octet-stream';
}

const server = http.createServer(async (request, response) => {
  const requestUrl = request.url || '/';
  const parsedUrl = new URL(requestUrl, `http://${request.headers.host}`);
  let pathname = parsedUrl.pathname;

  if (pathname === prefix) {
    pathname = `${prefix}/`;
  }

  if (!pathname.startsWith(`${prefix}/`)) {
    response.statusCode = 404;
    response.end('Not found');
    return;
  }

  let strippedPath = pathname.slice(prefix.length) || '/';
  let filePath = path.join(publicDir, strippedPath);

  try {
    const stats = await fs.stat(filePath);
    if (stats.isDirectory()) {
      if (!pathname.endsWith('/')) {
        response.writeHead(301, { Location: `${pathname}/` });
        response.end();
        return;
      }
      filePath = path.join(filePath, 'index.html');
    }
  } catch (error) {
    // missing path or file
  }

  try {
    const data = await fs.readFile(filePath);
    response.writeHead(200, {
      'Content-Type': getContentType(filePath),
      'Cache-Control': 'no-store',
    });
    response.end(data);
  } catch (error) {
    response.statusCode = 404;
    response.end('Not found');
  }
});

server.listen(port, '127.0.0.1', () => {
  console.log(`Serving static build from ${publicDir} at http://127.0.0.1:${port}${prefix}/`);
});

server.on('error', (error) => {
  console.error(error);
  process.exit(1);
});
