name: Add All Contributors

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install all-contributors-cli
        run: npm install -g all-contributors-cli

      - name: Configure Git
        run: |
          git config user.email "efox.web@gmail.com"
          git config user.name "EdenwareApps"

      - name: Add contributor
        run: |
          all-contributors add EdenwareApps code
          git commit -am "docs: add all contributors"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
