name: Update Contributors List

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          commit_message: "Update contributors list in README"
          readme_path: "README.md"        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
